
import com.mysql.cj.xdevapi.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Isuru
 */
public class manage_packages extends javax.swing.JFrame {
    
    
    Connection con=null;
    Statement st=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    

    /**
     * Creates new form ManageRoom
     */
    public manage_packages() {
        initComponents();
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","admin123");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(manage_packages.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ShowRecordInTable();
        
    }
    
    public void ShowRecordInTable(){
        int c=0;
        try {
            pst=con.prepareStatement("select * from packages");
            rs=pst.executeQuery();
            ResultSetMetaData rsmd=rs.getMetaData();
            c=rsmd.getColumnCount();
            DefaultTableModel DModel=(DefaultTableModel) jTable1.getModel();
            DModel.setRowCount(0);
            while (rs.next()){
                Vector column=new Vector();
                for(int i=1;i<=c;i++){
                column.add(rs.getString("id"));
                column.add(rs.getString("name"));
                column.add(rs.getString("cost_per_person"));
                column.add(rs.getString("description"));
                column.add(rs.getString("complementary"));
            }
                DModel.addRow(column);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(manage_packages.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtperperson = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdes = new javax.swing.JTextField();
        txtcomple = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        clearalldata = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName(""); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Room manage.png"))); // NOI18N
        jButton2.setText("Manage Packages");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 6, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Package ID");
        jLabel1.setMaximumSize(null);
        jLabel1.setMinimumSize(null);
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 180, 31));

        txtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid.setMaximumSize(null);
        txtid.setMinimumSize(null);
        txtid.setName(""); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 180, 33));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Package Name");
        jLabel2.setMaximumSize(null);
        jLabel2.setMinimumSize(null);
        jLabel2.setName(""); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 178, 31));

        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setMaximumSize(null);
        txtname.setMinimumSize(null);
        txtname.setName(""); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 178, 33));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cost Per Person");
        jLabel3.setMaximumSize(null);
        jLabel3.setMinimumSize(null);
        jLabel3.setName(""); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 178, 31));

        txtperperson.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtperperson.setMaximumSize(null);
        txtperperson.setMinimumSize(null);
        txtperperson.setName(""); // NOI18N
        getContentPane().add(txtperperson, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, 178, 33));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Description");
        jLabel4.setMaximumSize(null);
        jLabel4.setMinimumSize(null);
        jLabel4.setName(""); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 180, 31));

        txtdes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdes.setMaximumSize(null);
        txtdes.setMinimumSize(null);
        txtdes.setName(""); // NOI18N
        getContentPane().add(txtdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 180, 33));

        txtcomple.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcomple.setMaximumSize(null);
        txtcomple.setMinimumSize(null);
        txtcomple.setName(""); // NOI18N
        getContentPane().add(txtcomple, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, 180, 33));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Complementary ");
        jLabel5.setMaximumSize(null);
        jLabel5.setMinimumSize(null);
        jLabel5.setName(""); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 180, 31));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "name", "cost_per_person", "description", "complementary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1080, 340));

        clearalldata.setBackground(new java.awt.Color(255, 51, 51));
        clearalldata.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        clearalldata.setForeground(new java.awt.Color(255, 255, 255));
        clearalldata.setText("Clear All");
        clearalldata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearalldataActionPerformed(evt);
            }
        });
        getContentPane().add(clearalldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 170, 40));

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton5.setText("Add Package Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 170, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SemiBack.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new manage_packages().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();       
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearalldataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearalldataActionPerformed
        
            try {
                pst=con.prepareStatement("DELETE FROM packages");
                pst.executeUpdate();
                
            JOptionPane.showMessageDialog(this, "All data cleared from the table.", "Data Cleared", JOptionPane.INFORMATION_MESSAGE);

            ShowRecordInTable();
                

            } catch (SQLException ex) {
                Logger.getLogger(manage_packages.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_clearalldataActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
            if(txtid.getText().equals("")){
                JOptionPane.showMessageDialog(this, "All field is required!");
                txtid.requestFocus();
            }
            else if(txtname.getText().equals("")){
                JOptionPane.showMessageDialog(this, "All field is required!");
                txtname.requestFocus();

            }
            else{
                try {
                    pst=con.prepareStatement("select * from packages where Id=?");
                    pst.setString(1, txtid.getText());
                    rs=pst.executeQuery();
                    if(rs.next()){
                        JOptionPane.showMessageDialog(this, "Package id is already exist");
                    }else{
                        pst=con.prepareStatement("insert into packages(id,name,cost_per_person,description,complementary)values(?,?,?,?,?)");
                        pst.setString(1, txtid.getText());
                        pst.setString(2, txtname.getText());
                        pst.setString(3, txtperperson.getText());
                        pst.setString(4, txtdes.getText());
                        pst.setString(5, txtcomple.getText());
                        pst.executeUpdate();
                       JOptionPane.showMessageDialog(this, "Package added!");
                       ShowRecordInTable();
                       txtid.setText("");
                       txtname.setText("");
                       txtperperson.setText("");
                       txtdes.setText("");
                       txtcomple.setText("");



                    }
                } catch (SQLException ex) {
                    Logger.getLogger(manage_packages.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
                
         
            

// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manage_packages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manage_packages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manage_packages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manage_packages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manage_packages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearalldata;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcomple;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtperperson;
    // End of variables declaration//GEN-END:variables
}
